name: lerobot
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - jpeg=9f=h5ce9db8_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.8.1=h13d4d48_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.5=h7934f7d_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.1.0
      - blinker==1.9.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.87.0.1
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-qhull==8.0.2.1
      - cmeel-tinyxml2==10.0.0
      - cmeel-urdfdom==4.0.1
      - cmeel-zlib==1.3.1
      - coal-library==3.0.1
      - contourpy==1.3.2
      - coverage==7.10.7
      - cycler==0.12.1
      - cython==3.1.4
      - datasets==3.6.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - deepdiff==8.6.1
      - diffusers==0.35.1
      - dill==0.3.8
      - distlib==0.4.0
      - dm-control==1.0.14
      - dm-env==1.6
      - dm-tree==0.1.9
      - docopt==0.6.2
      - draccus==0.10.0
      - dynamixel-sdk==3.8.4
      - eigenpy==3.10.3
      - einops==0.8.1
      - eiquadprog==1.2.9
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - farama-notifications==0.0.4
      - feetech-servo-sdk==1.0.0
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - grpcio==1.75.1
      - grpcio-tools==1.73.1
      - gym-aloha==0.1.1
      - gym-hil==0.1.11
      - gym-pusht==0.1.5
      - gymnasium==0.29.1
      - gymnasium-robotics==1.2.4
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - hidapi==0.14.0.post4
      - huggingface-hub==0.35.3
      - identify==2.6.14
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - ipython==8.37.0
      - ischedule==1.2.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - lazy-loader==0.4
      - lerobot==0.3.3
      - lxml==6.0.2
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mergedeep==1.3.4
      - meshcat==0.3.2
      - mock-serial==0.0.1
      - mpmath==1.3.0
      - mujoco==2.3.7
      - multidict==6.6.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - num2words==0.5.14
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pettingzoo==1.24.3
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==12.0.0
      - pin==3.4.0
      - placo==0.9.14
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.33.0
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pygments==2.19.2
      - pymunk==6.11.1
      - pyngrok==7.4.0
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyrealsense2==2.56.5.9235
      - pyserial==3.5
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - pyzmq==27.1.0
      - regex==2025.9.18
      - requests==2.32.5
      - rerun-sdk==0.22.1
      - rhoban-cmeel-jsoncpp==1.9.4.9
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - sentry-sdk==2.39.0
      - setuptools==80.9.0
      - shapely==2.1.2
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - tifffile==2025.5.10
      - tokenizers==0.21.4
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.7.1
      - torchcodec==0.5
      - torchvision==0.22.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.3.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - u-msgpack-python==2.8.0
      - urllib3==2.5.0
      - virtualenv==20.34.0
      - wandb==0.22.0
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/oooer/miniconda3/envs/lerobot
